interface BaseFrontmatter {
  uuid: String!
  createdAt: Date!
  updatedAt: Date!
}

type ArticleFrontmatter implements Node & BaseFrontmatter @dontInfer {
  uuid: String!
  draft: Boolean!
  title: String!
  path: String!
  createdAt: Date!
  updatedAt: Date!
  links: [String!]
  featuredImage: File! @fileByRelativePath
}

type ActorFrontmatter implements Node & BaseFrontmatter @dontInfer {
  uuid: String!
  fullName: String
  username: String
  avatar: File @fileByRelativePath
  color: String
  createdAt: Date!
  updatedAt: Date!
}

type GroupFrontmatter implements Node & BaseFrontmatter @dontInfer {
  uuid: String!
  name: String!
  type: String!
  avatar: File! @fileByRelativePath
  members: [ActorFrontmatter!]
  color: String
  createdAt: Date!
  updatedAt: Date!
}

type PageFrontmatter implements Node & BaseFrontmatter @dontInfer {
  uuid: String!
  title: String!
  path: String!
  slug: String!
  createdAt: Date!
  updatedAt: Date!
}

# Topics
type TopicFrontmatter implements Node & BaseFrontmatter @dontInfer {
  uuid: String!
  slug: String!
  label: String!
  color: String
  createdAt: Date!
  updatedAt: Date!
}

type ImageAndDescription {
  description: String
  image: File!
}

type AreaFrontmatter implements Node & BaseFrontmatter @dontInfer {
  uuid: String!
  label: String!
  color: String!
  groups: [GroupFrontmatter!]
  topics: [TopicFrontmatter!]
  polygon: String!
  createdAt: Date!
  updatedAt: Date!
}

type ProjectFrontmatter implements Node & BaseFrontmatter @dontInfer {
  uuid: String!
  name: String!
  date: Date!
  color: String!
  startDate: Date!
  endDate: Date
  areas: [String!]
  images: [ImageAndDescription!]
  createdAt: Date!
  updatedAt: Date!
}

# Events
type EventFrontmatter implements Node & BaseFrontmatter @dontInfer {
  uuid: String!
  title: String!
  date: Date!
  type: String
  location: String
  groups: [GroupFrontmatter!]
  topics: [TopicFrontmatter!]
  actors: [ActorFrontmatter!]
  links: [String!]
  images: [ImageAndDescription!]
  createdAt: Date!
  updatedAt: Date!
}

type MdxFrontmatter implements BaseFrontmatter {
  uuid: String!
  createdAt: Date!
  updatedAt: Date!
}

type Mdx implements Node {
  frontmatter: Frontmatter
}
