name: Setup Workspace
description: Checkout, install deps, and build packages with content-based caching

inputs:
  hash:
    required: true
    description: "The hash obtained from hashFiles('**/pnpm-lock.yaml')"

runs:
  using: "composite"
  steps:
    - uses: ./.github/actions/install-deps
      with:
        hash: ${{ inputs.hash }}

    - uses: ./.github/actions/build-packages
