export default {
  extends: ["@commitlint/config-conventional"],
  rules: {
    "scope-case": [2, "always", "lowerCase"],
    "scope-enum": [
      2,
      "always",
      [
        "workspace",
        "deps",
        "deps-dev",
        "core",
        "shared",
        "test",
        "backend",
        "ui",
        "web",
        "admin",
        "api",
        "worker",
        "ai-bot",
        "agent",
        "storybook",
        "localai",
      ],
    ],
    "type-enum": [
      2,
      "always",
      [
        "feat",
        "fix",
        "docs",
        "chore",
        "refactor",
        "revert",
        "ci",
        "test",
        "release",
        "build",
      ],
    ],
  },
};
