services:
  # reverseproxy.dev:
  #   restart: always
  #   image: nginxproxy/nginx-proxy:1.6
  #   ports:
  #     - "80:80"
  #     # - 127.0.0.1:443:443
  #   volumes:
  #     - ./resources/reverse-proxy/default.conf:/etc/nginx/conf.d/custom-settings.conf:ro
  #     - ./_data/html:/usr/share/nginx/html:rw
  #     - ./_data/certs:/etc/nginx/certs:rw
  #     - ./_data/logs:/var/log/nginx:rw
  #     - /var/run/docker.sock:/tmp/docker.sock:ro
  #   environment:
  #     DEFAULT_HOST: liexp.dev
  #   networks:
  #     - reverseproxy

  telegram-bot-api:
    image: aiogram/telegram-bot-api:latest
    env_file:
      - ./services/api/.env.local
    environment:
      # TELEGRAM_STAT: 1
      TELEGRAM_VERBOSITY: 1
      TELEGRAM_LOCAL: 1
      TELEGRAM_HTTP_IP_ADDRESS: "[::]"
      # VIRTUAL_HOST: telegram.liexp.dev
      # VIRTUAL_PORT: 8081
    tty: false
    stdin_open: true
    volumes:
      - telegram-bot-api-data:/var/lib/telegram-bot-api
    ports:
      - "127.0.0.1:8081:8081"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-file: 5
        max-size: 10m
    networks:
      - reverseproxy

  telegram.liexp.dev:
    restart: always
    image: nginx:1.25.4-alpine
    volumes:
      - ./resources/nginx/telegram-bot-api-dev.conf:/etc/nginx/conf.d/default.conf:ro
      - telegram-bot-api-data:/var/lib/telegram-bot-api:ro
    environment:
      NGINX_SERVER_NAME: telegram.liexp.dev
      VIRTUAL_HOST: telegram.liexp.dev
      VIRTUAL_PORT: 9008
    depends_on:
      - telegram-bot-api
    ports:
      - "127.0.0.1:9008:9008"
    networks:
      - reverseproxy

networks:
  reverseproxy:
    external: true

volumes:
  telegram-bot-api-data:
