packages:
  - packages/@liexp/*
  - services/api
  - services/worker
  - services/ai-bot
  - services/web
  - services/admin-web
  - services/storybook

onlyBuiltDependencies:
  - exifreader
  - esbuild

publicHoistPattern:
  - "*vite*"
  - "*rollup*"
  - "*eslint*"
  - "*prettier*"

nodeLinker: hoisted
linkWorkspacePackages: deep
preferWorkspacePackages: true

# keep the PNPM legacy workspace hoisting behavior
injectWorkspacePackages: false
