packages:
  - packages/@liexp/*
  - services/api
  - services/worker
  - services/ai-bot
  - services/web
  - services/admin-web
  - services/storybook

onlyBuiltDependencies:
  - exifreader
  - esbuild
  - sharp

ignoredBuiltDependencies:
  - "@parcel/watcher"
  - cpu-features
  - protobufjs
  - ssh2
  - unrs-resolver

publicHoistPattern:
  - "*vite*"
  - "*rollup*"
  - "*eslint*"
  - "*prettier*"

overrides:
  "react-is": "^18"

nodeLinker: hoisted
linkWorkspacePackages: deep
preferWorkspacePackages: true

# keep the PNPM legacy workspace hoisting behavior
injectWorkspacePackages: false
