packages:
  - packages/@liexp/*
  - services/api
  - services/worker
  - services/ai-bot
  - services/web
  - services/admin
  - services/storybook
  - services/agent

publicHoistPattern:
  - "*vite*"
  - "*rollup*"
  - "*eslint*"
  - "*prettier*"
  - "dotenv"
  - "@tiptap/core"

nodeLinker: hoisted
linkWorkspacePackages: true
preferWorkspacePackages: true

# keep the PNPM legacy workspace hoisting behavior
injectWorkspacePackages: false

syncInjectedDepsAfterScripts:
  - build

supportedArchitectures:
  os:
    - linux
  cpu:
    - x64
  libc:
    - glibc

overrides:
  "@ts-endpoint/core": "file:./patches/ts-endpoint-core-0.1.0.tgz"
  "@ts-endpoint/http-client": "file:./patches/ts-endpoint-http-client-0.1.0.tgz"
  "@ts-endpoint/resource-client": "file:./patches/ts-endpoint-resource-client-0.1.0.tgz"
  "@ts-endpoint/express": "file:./patches/ts-endpoint-express-0.1.0.tgz"
  "@ts-endpoint/react-admin": "file:./patches/ts-endpoint-react-admin-0.1.0.tgz"
  "@ts-endpoint/tanstack-query": "file:./patches/ts-endpoint-tanstack-query-0.1.0.tgz"
  zod: ^4.3.5
  dotenv: ^17.4.2
  tough-cookie@<4.1.3: '>=4.1.3'
  form-data@<2.5.4: '>=2.5.4'
  tar@<7.5.7: '>=7.5.7'
  tar@<=7.5.2: '>=7.5.3'
  tar@<7.5.8: '>=7.5.8'
  qs@<6.14.1: '>=6.14.1'
  tar@<=7.5.3: '>=7.5.11'
  lodash@>=4.0.0 <=4.17.23: '>=4.18.0'
  '@xmldom/xmldom@<0.8.12': '>=0.8.12'
  basic-ftp@<=5.2.1: '>=5.2.2'
  basic-ftp@=5.2.0: '>=5.2.1'
  dompurify@<=3.3.3: '>=3.4.0'
  basic-ftp@<=5.2.2: '>=5.3.0'

allowBuilds:
  canvas: false
  msw: false
  exifreader: true
  esbuild: true
  sharp: true
  '@parcel/watcher': false
  cpu-features: false
  protobufjs: false
  ssh2: false
  unrs-resolver: false
