packages:
  - packages/@liexp/*
  - services/api
  - services/worker
  - services/ai-bot
  - services/web
  - services/admin-web
  - services/storybook
catalog:
  "@aws-sdk/client-s3": ^3.741.0
  "@aws-sdk/client-sso-oidc": ^3.741.0
  "@aws-sdk/client-sts": ^3.741.0
  "@aws-sdk/lib-storage": ^3.741.0
  "@aws-sdk/s3-request-presigner": ^3.741.0
  "@aws-sdk/types": ^3.734.0
  "@blocknote/core": ^0.23.1
  "@blocknote/mantine": ^0.23.1
  "@blocknote/react": ^0.23.1
  "@blocknote/server-util": ^0.23.1
  "@commitlint/cli": ^19.7.1
  "@commitlint/config-conventional": ^19.7.1
  "@databases/escape-identifier": ^1.0.3
  "@databases/sql": ^3.3.0
  "@emotion/cache": ^11.14.0
  "@emotion/css": ^11.13.5
  "@emotion/react": ^11.14.0
  "@emotion/server": ^11.11.0
  "@emotion/styled": ^11.14.0
  "@emotion/utils": ^1.4.2
  "@eslint/js": ^9.19.0
  "@fortawesome/fontawesome-svg-core": ^6.7.2
  "@fortawesome/free-brands-svg-icons": ^6.7.2
  "@fortawesome/free-solid-svg-icons": ^6.7.2
  "@fortawesome/react-fontawesome": ^0.2.2
  "@langchain/community": ^0.3.28
  "@langchain/core": ^0.3.37
  "@langchain/openai": ^0.4.2
  "@mui/icons-material": ^6.4.2
  "@mui/lab": 6.0.0-beta.25
  "@mui/material": ^6.4.2
  "@mui/styles": ^6.4.2
  "@mui/system": ^6.1.7
  "@mui/x-data-grid": ^7.25.0
  "@napi-rs/canvas": ^0.1.66
  "@react-spring/web": ^9.7.4
  "@rollup/plugin-image": ^3.0.3
  "@storybook/addon-essentials": ^8.5.3
  "@storybook/addon-interactions": ^8.5.3
  "@storybook/addon-links": ^8.5.3
  "@storybook/builder-vite": ^8.5.3
  "@storybook/manager-api": ^8.5.3
  "@storybook/react": ^8.5.3
  "@storybook/react-vite": ^8.5.3
  "@storybook/theming": ^8.5.3
  "@tanstack/eslint-plugin-query": ^5.66.0
  "@tanstack/react-query": ^5.66.0
  "@types/body-parser": ^1.19.5
  "@types/compression": ^1.7.5
  "@types/cors": ^2.8.17
  "@types/d3": ^7.4.3
  "@types/d3-hierarchy": ^3.1.7
  "@types/d3-sankey": ^0.12.4
  "@types/d3-scale": ^4.0.8
  "@types/debug": ^4.1.12
  "@types/dockerode": ^3.3.34
  "@types/fluent-ffmpeg": "^2.1.27"
  "@types/eslint__js": ^8.42.3
  "@types/express": ^4.17.21
  "@types/jsdom": ^21.1.7
  "@types/jsonwebtoken": ^9.0.8
  "@types/lodash": ^4.17.15
  "@types/multer": ^1.4.12
  "@types/node": ^22.13.0
  "@types/node-cron": ^3.0.11
  "@types/node-telegram-bot-api": ^0.64.7
  "@types/pg": ^8.11.11
  "@types/prompts": ^2.4.9
  "@types/react": ^18.3.18
  "@types/react-dom": ^18.3.5
  "@types/react-slick": ^0.23.13
  "@types/react-virtualized": ^9.22.0
  "@types/supertest": ^6.0.2
  "@types/throttle-debounce": ^5.0.2
  "@types/topojson-client": ^3.1.5
  "@types/topojson-specification": ^1.0.5
  "@visx/axis": ^3.12.0
  "@visx/curve": ^3.12.0
  "@visx/event": ^3.12.0
  "@visx/geo": ^3.12.0
  "@visx/gradient": ^3.12.0
  "@visx/grid": ^3.12.0
  "@visx/group": ^3.12.0
  "@visx/heatmap": ^3.12.0
  "@visx/hierarchy": ^3.12.0
  "@visx/legend": ^3.12.0
  "@visx/network": ^3.12.0
  "@visx/responsive": ^3.12.0
  "@visx/scale": ^3.12.0
  "@visx/shape": ^3.12.0
  "@visx/text": ^3.12.0
  "@visx/threshold": ^3.12.0
  "@visx/tooltip": ^3.12.0
  "@visx/wordcloud": ^3.12.0
  "@visx/zoom": ^3.12.0
  "@vitejs/plugin-react": ^4.3.4
  "@vitest/coverage-v8": ^3.0.5
  "@xyflow/react": ^12.4.2
  axios: ^1.7.9
  body-parser: ^1.20.3
  bs58: ^6.0.0
  cheerio: ^1.0.0
  clsx: ^2.1.0
  compression: ^1.7.4
  corepack: ^0.31.0
  cors: 2.8.5
  cronstrue: ^2.54.0
  d3: ^7.9.0
  d3-hierarchy: ^3.1.2
  d3-sankey: ^0.12.3
  d3-scale: ^4.0.2
  date-fns: ^4.1.0
  debug: ^4.4.0
  dockerode: ^4.0.4
  domino: ^2.1.0
  dotenv: ^16.4.7
  entitree-flex: ^0.4.1
  esbuild: ^0.24.2
  eslint: ^9.19.0
  eslint-import-resolver-typescript: ^3.7.0
  eslint-plugin-fp-ts: ^0.3.2
  eslint-plugin-import: ^2.31.0
  eslint-plugin-prettier: ^5.2.3
  eslint-plugin-react: ^7.37.4
  exifreader: ^4.26.1
  express: ^4.21.0
  express-jwt: ^8.5.1
  express-unless: ^2.1.3
  fast-check: ^2.25.0
  fast-check-io-ts: ^0.5.0
  fast-csv: ^5.0.2
  fluent-ffmpeg: ^2.1.2
  fp-ts: ^2.16.9
  globals: ^15.14.0
  husky: ^9.1.7
  instagram-private-api: ^1.46.1
  io-ts: ^2.2.22
  io-ts-types: ^0.5.19
  ioredis: ^5.4.2
  jsdom: ^26.0.0
  jsonwebtoken: ^9.0.2
  knip: ^5.43.6
  langchain: ^0.3.15
  lint-staged: ^15.4.3
  lodash: ^4.17.21
  multer: ^1.4.5-lts.1
  node-cron: ^3.0.3
  node-telegram-bot-api: ^0.66.0
  nodemw: ^0.23.0
  ol: ^10.4.0
  openai: ^4.82.0
  page-metadata-parser: ^1.1.4
  parse2-kmz: ^1.0.7
  path-to-regexp: ^8.2.0
  pdfjs-dist: ^4.10.38
  pg: ^8.11.5
  prettier: ^3.4.2
  prompts: ^2.4.2
  puppeteer-core: ^24.1.1
  puppeteer-extra: ^3.3.6
  puppeteer-extra-plugin-stealth: ^2.11.2
  query-string: ^7.1.3
  ra-core: ^5.5.3
  ra-i18n-polyglot: ^5.5.3
  ra-language-english: ^5.5.3
  react: ^18.3.1
  react-admin: ^5.5.3
  react-audio-player: ^0.17.0
  react-dom: ^18.3.1
  react-dropzone: ^14.3.5
  react-error-boundary: ^5.0.0
  react-helmet-async: ^2.0.5
  react-hook-form: ^7.54.1
  react-router: ^6.28.1
  react-router-dom: ^6.28.1
  react-share: ^5.2.0
  react-slick: ^0.30.3
  react-toc: ^3.1.0
  react-virtualized: ^9.22.6
  reflect-metadata: ^0.2.2
  serve: ^14.2.4
  sharp: ^0.33.5
  sirv: ^3.0.0
  slick-carousel: ^1.8.1
  storybook: ^8.5.3
  supertest: ^7.0.0
  throttle-debounce: ^5.0.0
  topojson-client: ^3.1.0
  ts-endpoint: ^2.0.0
  ts-endpoint-express: ^2.0.0
  ts-io-error: ^2.0.0
  ts-shared: ^2.0.0-alpha.6
  tsx: ^4.19.2
  typelevel-ts: ^0.4.0
  typeorm: ^0.3.20
  typescript: ^5.7.3
  typescript-eslint: ^8.23.0
  uuid: ^11.0.5
  vanilla-jsoneditor: ^2.3.3
  vite: ^6.1.0
  vite-plugin-css-injected-by-js: ^3.5.2
  vite-plugin-optimizer: ^1.4.3
  vite-tsconfig-paths: ^5.1.4
  vitest: ^3.0.5
  vitest-mock-extended: ^2.0.2
  waveform-data: ^4.5.0
  web-vitals: ^4.2.4
  wink-eng-lite-web-model: ^1.8.0
  wink-nlp: ^2.3.0
  wink-nlp-utils: ^2.1.0
