packages:
  - packages/@liexp/*
  - services/api
  - services/worker
  - services/ai-bot
  - services/web
  - services/admin
  - services/storybook
  - services/agent

onlyBuiltDependencies:
  - exifreader
  - esbuild
  # - sharp

ignoredBuiltDependencies:
  - "@parcel/watcher"
  - cpu-features
  - protobufjs
  - ssh2
  - unrs-resolver

publicHoistPattern:
  - "*vite*"
  - "*rollup*"
  - "*eslint*"
  - "*prettier*"

overrides:
  "react-is": "^18"

nodeLinker: hoisted

injectWorkspacePackages: true
preferWorkspacePackages: true
linkWorkspacePackages: deep
syncInjectedDepsAfterScripts:
- build

supportedArchitectures:
  os:
    - current
  cpu:
    - current
  libc:
    - current
