export * as Actor from "./actor.endpoints";
export * as Area from './area.endpoints'
export * as Article from "./article.endpoints";
export * as Event from "./event.endpoints";
export * as Graph from "./graph.endpoints";
export * as Group from "./group.endpoints";
export * as GroupMember from "./GroupMember.endpoints";
export * as Page from "./page.endpoints";
export * as Project from "./project.endpoints";
export * as ProjectImage from './ProjectImage.endpoints';
export * as Uploads from "./upload.endpoints";
export * as User from './User.endpoints'