apiVersion: v1
kind: ConfigMap
data:
  ai-bot.config.json: |
    {
      "api": {
        "url": "http://api.prod.svc.cluster.local/v1",
        "mcp": "http://api.prod.svc.cluster.local/mcp"
      },
      "agent": {
        "url": "http://agent.prod.svc.cluster.local/v1"
      }
    }

metadata:
  name: ai-bot-config-map
  namespace: {{ .Release.Namespace }}
{{ tuple . "ai-bot-config-map" | include "aiBot.labels" | indent 2 }}
