version: "3"

services:

  api:
    image: ghcr.io/lies-exposed/liexp-api:alpha-latest
    container_name: liexp-api
    user: $API_UID:$API_GID
    env_file:
      # - ../.env.alpha
      - .env.api
    environment:
      - DEBUG=@liexp*
    ports:
      - "4010:4010"
    volumes:
      # - ../services/api/certs/:/app/services/api/certs/:ro
      - ./certs/:/app/services/api/certs/:ro
      - ./temp/:/app/services/api/temp/:rw
      - ./config/:/app/services/api/config/:rw
      - bot-brother-storage:/app/node_modules/bot-brother/__storage
    working_dir: /app/services/api
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4010/v1/healthcheck"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 30s
    command: yarn start
    restart: always

  web:
    image: ghcr.io/lies-exposed/liexp-web:alpha-latest
    container_name: liexp-web
    env_file:
      # - ../services/web/.env
      - .env.web
    environment:
      API_URL: http://api:4010/v1
      ADMIN_URL: https://alpha.lies.exposed/admin
    ports:
      - "4020:4020"
    links:
      - api
    working_dir: /app/services/web
    command: yarn serve
    restart: always

volumes:
  bot-brother-storage: {}