services:

  api:
    image: ghcr.io/lies-exposed/liexp-api:alpha-latest
    container_name: liexp-api
    user: $API_UID:$API_GID
    env_file:
      - .env.api
    ports:
      - "127.0.0.1:4010:4010"
    # expose:
    #   - 4010
    volumes:
      - ./certs/:/prod/services/api/certs/:ro
      - ./temp/:/prod/services/api/temp/:rw
      - ./temp/db/:/prod/services/api/db/:rw
      - ./config/:/prod/services/api/config/:rw
    working_dir: /prod/services/api
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4010/v1/healthcheck"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 30s
    command: pnpm start
    restart: always
    depends_on:
      - telegram-bot-api
    logging:
      driver: "json-file"
      options:
          max-file: 5
          max-size: 10m

  web:
    image: ghcr.io/lies-exposed/liexp-web:alpha-latest
    container_name: liexp-web
    env_file:
      - .env.web
    environment:
      VIRTUAL_HOST: 0.0.0.0
      VIRTUAL_PORT: 4020
    ports:
      - "127.0.0.1:4020:4020"
    # expose:
    #   - "4020"
    depends_on:
      - api
    working_dir: /prod/services/web
    command: pnpm serve
    restart: always
    logging:
      driver: "json-file"
      options:
          max-file: 5
          max-size: 10m

  telegram-bot-api:
    image: aiogram/telegram-bot-api:latest
    env_file:
      - .env.api
    environment:
      TELEGRAM_API_ID: ${TELEGRAM_API_ID}
      TELEGRAM_API_HASH: ${TELEGRAM_API_HASH}
      TELEGRAM_LOCAL: "true"
    volumes:
      - telegram-bot-api-data:/var/lib/telegram-bot-api
    ports:
      - "127.0.0.1:8081:8081"
    restart: on-failure
    logging:
      driver: "json-file"
      options:
          max-file: 5
          max-size: 10m

  # telegram-bot:
  #   image: nginx:1.25.4-alpine
  #   restart: always
  #   depends_on:
  #     - telegram-bot-api
  #   volumes:
  #     - ./telegram-bot-nginx-log:/var/log/nginx/
  #     - telegram-bot-api-data:/var/lib/telegram-bot-api
  #     - ./nginx/telegram-bot-api.conf:/etc/nginx/conf.d/default.conf
  #   ports:
  #     - "9008:9008"


volumes:
  telegram-bot-api-data: {}