apiVersion: v1
kind: Secret
metadata:
  name: bugsink-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    lies.exposed/name: bugsink-secrets
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/namespace: {{ .Release.Namespace | quote }}
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  SECRET_KEY: {{ .Values.bugsink.secretKey | b64enc | quote }}
  CREATE_SUPERUSER: {{ .Values.bugsink.superuser | b64enc | quote }}
{{- if .Values.bugsink.email.hostUser }}
  EMAIL_PASSWORD: {{ .Values.bugsink.email.password | b64enc | quote }}
{{- end }}