import { extendBaseConfig } from "./src/test/vitest.base-config";

export default extendBaseConfig(import.meta.url, (toAlias) => ({
  test: {
    name: "@liexp/backend",
    globals: true,
    include: [toAlias("src/**/*.spec.ts")],
    watch: false,
    coverage: {
      include: ["src/**/*.ts"],
      exclude: [
        "src/test",
        "src/queries/**",
        "src/scrapers/**",
        "src/pubsub/**",
        "src/services/agent-chat/**",
        "src/context/**",
        "src/clients/**",
        "src/flows/admin/**",
        "src/flows/ai/**",
        "src/flows/media/thumbnails/**",
        "src/flows/media/admin/**",
        "src/express/vite/ssr-handler.ts",
        "src/express/vite/types.ts",
        "src/express/index.ts",
        "src/express/routes/*/index.ts",
        "src/errors/index.ts",
        "src/middleware/**",
        "src/providers/ai/**",
        "src/providers/ig/**",
        "src/providers/ner/**",
        "src/providers/space/**",
        "src/providers/wikipedia/**",
        "src/providers/orm/index.ts",
        "src/providers/orm/orm.provider.ts",
        "src/providers/redis/redis.provider.ts",
        "src/providers/redis/Subscriber.ts",
      ],
      thresholds: {
        lines: 50,
        statements: 50,
        functions: 50,
      },
    },
  },
}));
