import "@fortawesome/fontawesome-svg-core/styles.css";
import { library } from "@fortawesome/fontawesome-svg-core";
import {
  fab,
  faGithub,
  faInstagram,
  faPaypal,
  faTelegram,
} from "@fortawesome/free-brands-svg-icons";
import {
  faAlignCenter,
  faAlignJustify,
  faAlignLeft,
  faAlignRight,
  faBarcode,
  faBold,
  faBook,
  faCalendar,
  faCircleDollarToSlot,
  faCode,
  faEdit,
  faFileImage,
  faFilm,
  faFlask,
  faHashtag,
  faHeader,
  faItalic,
  faLink,
  faMapLocation,
  faMoneyBill1Wave,
  faParagraph,
  faPersonHalfDress,
  faQuoteLeft,
  faRemove,
  faShareNodes,
  faSkullCrossbones,
  faTextHeight,
  faUnderline,
  faUser,
  faUserFriends,
  faUserGroup,
  faUsersBetweenLines,
} from "@fortawesome/free-solid-svg-icons";

library.add(
  ...([
    // brands
    fab,
    faGithub,
    faPaypal,
    faTelegram,
    faInstagram,
    // solid
    faCalendar,
    faFlask,
    faQuoteLeft,
    faCircleDollarToSlot,
    faSkullCrossbones,
    faEdit,
    faBook,
    faBarcode,
    faLink,
    faFilm,
    faMoneyBill1Wave,
    faBold,
    faParagraph,
    faHeader,
    faRemove,
    faAlignCenter,
    faAlignJustify,
    faAlignLeft,
    faAlignRight,
    faTextHeight,
    faItalic,
    faUnderline,
    faCode,
    faLink,
    faAlignJustify,
    faUser,
    faUserFriends,
    faFileImage,
    faHashtag,
    faPersonHalfDress,
    faUserGroup,
    faUsersBetweenLines,
    faUser,
    faShareNodes,
    faMapLocation,
  ] as any[]),
);
