environments:
  default:
  prod:

releases:
  - name: lies-exposed
    namespace: "{{ if eq .Environment.Name \"prod\" }}prod{{ else }}liexp-dev{{ end }}"
    kubeContext: "home-server-local"
    chart: ../helm
    missingFileHandler: Warn
    values:
      - ../helm/values.yaml
      - ../helm/values.{{ .Environment.Name }}.yaml
    cleanupOnFail: true
    atomic: false
    timeout: 600
