import { type Router } from "express";
import { CreateEventRoute } from "./createEvent.controller.js";
import { DeleteEventRoute } from "./deleteEvent.controller.js";
import { DeleteEventSuggestionRoute } from "./deleteEventSuggestion.controller.js";
import { EditEventRoute } from "./editEvent.controller.js";
import { GetEventRoute } from "./getEvent.controller.js";
import { GetEventFromLinkRoute } from "./getEventFromLink.controller.js";
import { SearchEventRoute } from "./searchEvents.controller.js";
import { SearchEventsFromProviderRoute } from "./searchEventsFromProviders.controller.js";
import { CreateEventFromSuggestionRoute } from "./suggestions/createEventFromSuggestion.controller.js";
import { CreateEventSuggestionRoute } from "./suggestions/createEventSuggestion.controller.js";
import { EditEventSuggestionRoute } from "./suggestions/editEventSuggestion.controller.js";
import { GetEventSuggestionRoute } from "./suggestions/getEventSuggestion.controller.js";
import { GetEventSuggestionListRoute } from "./suggestions/getEventSuggestionList.controller.js";
import { type RouteContext } from "#routes/route.types.js";

export const MakeEventRoutes = (router: Router, ctx: RouteContext): void => {
  // MakeCreateEventFromLinkRoute(router, ctx);
  CreateEventFromSuggestionRoute(router, ctx);
  SearchEventsFromProviderRoute(router, ctx);
  CreateEventSuggestionRoute(router, ctx);
  CreateEventRoute(router, ctx);
  EditEventSuggestionRoute(router, ctx);
  EditEventRoute(router, ctx);
  DeleteEventSuggestionRoute(router, ctx);
  SearchEventRoute(router, ctx);
  GetEventSuggestionRoute(router, ctx);
  GetEventSuggestionListRoute(router, ctx);
  GetEventRoute(router, ctx);
  GetEventFromLinkRoute(router, ctx);
  DeleteEventRoute(router, ctx);
};
