import { Router } from "express";
import { CreateEventRoute } from "./createEvent.controller";
import { CreateEventFromSuggestionRoute } from "./createEventFromSuggestion.controller";
import { CreateEventSuggestionRoute } from "./createEventSuggestion.controller";
import { DeleteEventRoute } from "./deleteEvent.controller";
import { DeleteEventSuggestionRoute } from "./deleteEventSuggestion.controller";
import { EditEventRoute } from "./editEvent.controller";
import { EditEventSuggestionRoute } from "./editEventSuggestion.controller";
import { GetEventRoute } from "./getEvent.controller";
import { GetEventFromLinkRoute } from "./getEventFromLink.controller";
import { PostEventToPlatformRoute } from "./postEventToPlatform.controller";
import { SearchEventRoute } from "./searchEvents.controller";
import { SearchEventsFromProviderRoute } from './searchEventsFromProviders.controller';
import { GetEventSuggestionRoute } from "./suggestions/getEventSuggestion.controller";
import { GetEventSuggestionListRoute } from "./suggestions/getEventSuggestionList.controller";
import { RouteContext } from "@routes/route.types";

export const MakeEventRoutes = (router: Router, ctx: RouteContext): void => {
  // MakeCreateEventFromLinkRoute(router, ctx);
  CreateEventFromSuggestionRoute(router, ctx);
  SearchEventsFromProviderRoute(router, ctx);
  CreateEventSuggestionRoute(router, ctx);
  CreateEventRoute(router, ctx);
  PostEventToPlatformRoute(router, ctx);
  EditEventSuggestionRoute(router, ctx);
  EditEventRoute(router, ctx);
  DeleteEventSuggestionRoute(router, ctx);
  SearchEventRoute(router, ctx);
  GetEventSuggestionRoute(router, ctx);
  GetEventSuggestionListRoute(router, ctx);
  GetEventRoute(router, ctx);
  GetEventFromLinkRoute(router, ctx);
  DeleteEventRoute(router, ctx);
};
