#!/bin/sh

docker compose up -d db.liexp.dev
pnpm build && pnpm knip && pnpm --filter=...[HEAD^] lint --quiet && pnpm --filter=...[HEAD^] build && pnpm vitest --changed=HEAD^ && . "./scripts/healthcheck.sh"
