#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

yarn clean
yarn build
yarn lint
docker compose up -d db-test
sleep 10
yarn api jest --runInBand --bail --logHeapUsage
docker compose stop db-test
docker compose rm --volumes -f db-test
