name: "Build API"
description: "Build ./services/api when no cache is hit"

inputs:
  hash:
    required: true
    description: The suffix used to create the cache key

runs:
  using: "composite"
  steps:
    - uses: actions/cache@v3
      id: api-build
      with:
        path: services/api/build
        key: linux-api-build-${{ inputs.hash }}

    - name: Build API
      if: steps.api-build.outputs.cache-hit != 'true'
      run: yarn api build
      shell: bash
