name: "Build API"
description: "Build ./services/api with content-based caching"

outputs:
  cache-hit:
    description: "Whether the cache was hit"
    value: ${{ steps.api-build.outputs.cache-hit }}

runs:
  using: "composite"
  steps:
    - name: Compute API hash
      id: hash
      shell: bash
      run: |
        # Hash API source files + built packages (dependencies)
        API_HASH=$(find services/api/src -type f \( -name "*.ts" -o -name "*.tsx" \) 2>/dev/null | sort | xargs cat 2>/dev/null | sha256sum | cut -d' ' -f1)
        PACKAGES_HASH=$(find packages -type f -name "*.js" -path "*/lib/*" 2>/dev/null | sort | xargs cat 2>/dev/null | sha256sum | cut -d' ' -f1)
        COMBINED="${API_HASH:0:8}-${PACKAGES_HASH:0:8}"
        echo "api_hash=${COMBINED}" >> $GITHUB_OUTPUT

    - uses: actions/cache@v5
      id: api-build
      with:
        path: services/api/build
        key: linux-api-build-${{ steps.hash.outputs.api_hash }}
        restore-keys: |
          linux-api-build-

    - name: Build API
      if: steps.api-build.outputs.cache-hit != 'true'
      run: pnpm api build
      shell: bash
