/* eslint-disable no-restricted-imports */
import { TreeView, TreeItem } from "@mui/lab";
import {
  Accordion,
  AccordionDetails,
  AccordionSummary,
  Alert,
  AppBar,
  Autocomplete,
  type AutocompleteRenderInputParams,
  List,
  ListItem,
  ListItemButton,
  ListItemIcon,
  ListItemText,
  ListSubheader,
  type InputProps,
  type AutocompleteInputChangeReason,
  type AutocompleteProps,
  type ListProps,
  Box,
  type BoxProps,
  Breadcrumbs,
  Button,
  type ButtonProps,
  Card,
  CardActionArea,
  CardActions,
  type CardProps,
  Divider,
  DialogActions,
  Collapse,
  CssBaseline,
  CardContent,
  CardHeader,
  CardMedia,
  Checkbox,
  Chip,
  type ChipProps,
  CircularProgress,
  ClickAwayListener,
  Container,
  Dialog,
  DialogContent,
  Drawer,
  DialogTitle,
  FormControl,
  FormControlLabel,
  FormGroup,
  Grid,
  Grow,
  IconButton,
  type IconProps,
  Input,
  InputLabel,
  LinearProgress,
  Link,
  MenuItem,
  type MenuItemProps,
  MenuList,
  Modal,
  type ModalProps,
  Pagination,
  Paper,
  Popper,
  Select,
  type SelectChangeEvent,
  Slider,
  Stack,
  Switch,
  Tab,
  Tabs,
  TextField,
  type TextFieldProps,
  Toolbar,
  Tooltip,
  Typography,
  type TypographyProps,
  type TypographyOwnProps,
  Avatar,
  type AvatarProps,
  Popover,
  type PopoverProps,
  useMediaQuery as useMuiMediaQuery,
  ThemeProvider,
} from "@mui/material";
import { alpha } from "@mui/system";
import * as MUIIcons from "./icons.js";

export {
  Accordion,
  AccordionDetails,
  AccordionSummary,
  Alert,
  AppBar,
  Avatar,
  type AvatarProps,
  Autocomplete,
  type AutocompleteRenderInputParams,
  type InputProps,
  Box,
  Breadcrumbs,
  Button,
  type ButtonProps,
  Card,
  CardActionArea,
  CardActions,
  CardContent,
  CardHeader,
  CardMedia,
  Checkbox,
  // components
  Chip,
  CircularProgress,
  ClickAwayListener,
  Container,
  Collapse,
  CssBaseline,
  Dialog,
  DialogActions,
  Drawer,
  DialogContent,
  DialogTitle,
  Divider,
  FormControl,
  FormControlLabel,
  FormGroup,
  Grid,
  Grow,
  IconButton,
  Input,
  InputLabel,
  LinearProgress,
  Link,
  List,
  ListItem,
  ListItemButton,
  ListItemIcon,
  ListItemText,
  ListSubheader,
  MenuItem,
  MenuList,
  Modal,
  MUIIcons as Icons,
  Pagination,
  Paper,
  Popper,
  Popover,
  type PopoverProps,
  Select,
  Slider,
  Stack,
  Switch,
  Tab,
  Tabs,
  TextField,
  ThemeProvider,
  Toolbar,
  Tooltip,
  TreeItem,
  TreeView,
  Typography,
  type TypographyOwnProps,
  alpha,
  // colors
  useMuiMediaQuery,
  type AutocompleteInputChangeReason,
  type AutocompleteProps,
  type BoxProps,
  type CardProps,
  type ChipProps,
  type IconProps,
  type ListProps,
  type MenuItemProps,
  type ModalProps,
  type SelectChangeEvent,
  type TextFieldProps,
  type TypographyProps,
};
