/* eslint-disable no-restricted-imports */

import { TreeView, TreeItem } from "@mui/lab";
import {
  Accordion,
  AccordionDetails,
  AccordionSummary,
  AppBar,
  Autocomplete,
  type AutocompleteRenderInputParams,
  List,
  ListItem,
  ListItemButton,
  ListItemText,
  ListSubheader,
  type InputProps,
  type AutocompleteInputChangeReason,
  type AutocompleteProps,
  type ListProps,
  Box,
  type BoxProps,
  Breadcrumbs,
  Button,
  ButtonGroup,
  Card,
  CardActionArea,
  CardActions,
  type CardProps,
  Divider,
  DialogContentText,
  DialogActions,
  CssBaseline,
  CardContent,
  CardHeader,
  CardMedia,
  Checkbox,
  Chip,
  type ChipProps,
  CircularProgress,
  ClickAwayListener,
  Container,
  Dialog,
  DialogContent,
  DialogTitle,
  FormControl,
  FormControlLabel,
  FormGroup,
  Grid,
  Grow,
  Icon,
  IconButton,
  type IconProps,
  Input,
  InputLabel,
  Link,
  Menu,
  MenuItem,
  type MenuItemProps,
  MenuList,
  Modal,
  type ModalProps,
  Pagination,
  Paper,
  Popper,
  Select,
  type SelectChangeEvent,
  Slider,
  Stack,
  Switch,
  Tab,
  Tabs,
  TextField,
  type TextFieldProps,
  Toolbar,
  Typography,
  type TypographyProps,
  Avatar,
  type AvatarProps,
  Popover,
  type PopoverProps,
  StyledEngineProvider,
  ThemeProvider,
  useMediaQuery as useMuiMediaQuery,
} from "@mui/material";
import { alpha } from "@mui/system";
import * as MUIIcons from "./icons.js";

export {
  Accordion,
  AccordionDetails,
  AccordionSummary,
  AppBar,
  Avatar,
  type AvatarProps,
  Autocomplete,
  type AutocompleteRenderInputParams,
  type InputProps,
  Box,
  Breadcrumbs,
  Button,
  ButtonGroup,
  Card,
  CardActionArea,
  CardActions,
  CardContent,
  CardHeader,
  CardMedia,
  Checkbox,
  // components
  Chip,
  CircularProgress,
  ClickAwayListener,
  Container,
  CssBaseline,
  Dialog,
  DialogActions,
  DialogContent,
  DialogContentText,
  DialogTitle,
  Divider,
  FormControl,
  FormControlLabel,
  FormGroup,
  Grid,
  Grow,
  Icon,
  IconButton,
  MUIIcons as Icons,
  Input,
  InputLabel,
  Link,
  List,
  ListItem,
  ListItemButton,
  ListItemText,
  ListSubheader,
  Menu,
  MenuItem,
  MenuList,
  Modal,
  Pagination,
  Paper,
  Popper,
  Popover,
  type PopoverProps,
  Select,
  Slider,
  Stack,
  StyledEngineProvider,
  Switch,
  Tab,
  Tabs,
  TextField,
  ThemeProvider,
  Toolbar,
  TreeItem,
  TreeView,
  Typography,
  alpha,
  // colors
  useMuiMediaQuery,
  type AutocompleteInputChangeReason,
  type AutocompleteProps,
  type BoxProps,
  type CardProps,
  type ChipProps,
  type IconProps,
  type ListProps,
  type MenuItemProps,
  type ModalProps,
  type SelectChangeEvent,
  type TextFieldProps,
  type TypographyProps,
};
