name: Admin Web - Pull Request

on:
  pull_request:
    branches:
      - daily
      - release/alpha
      - master
    paths:
      - "packages/**"
      - "services/admin-web/**"

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "yarn"
          cache-dependency-path: yarn.lock

      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install modules
        # if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn

  lint:
    runs-on: ubuntu-latest
    needs: [install]
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "yarn"
          cache-dependency-path: yarn.lock

      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Lint code
        run: yarn admin-web lint

  build:
    runs-on: ubuntu-latest
    needs: [install]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "yarn"
          cache-dependency-path: yarn.lock

      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - uses: actions/cache@v2
        with:
          path: |
            packages/**/lib
            services/**/build
          key: admin-web-build

      - name: Type Check Web
        run: yarn admin-web tsc -b

      - name: Build admin web
        run: |
          yarn packages:build
          yarn admin-web build
