name: Admin Web - Pull Request

on:
  pull_request:
    branches:
      - daily
      - release/alpha
      - master
    paths:
      - ".github/workflows/**"
      - "packages/@liexp/**/src/**"
      - "services/admin-web/**"
env:
  ADMIN_WEB_IMAGE_NAME: liexp-admin-web

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/install-deps
        with:
          hash: ${{ hashFiles('**/yarn.lock') }}

  build-packages:
    uses: ./.github/workflows/packages-pull-request.yml
    needs: install

  lint:
    runs-on: ubuntu-latest
    needs: [install, build-packages]
    steps:
      - uses: actions/checkout@v4

      - name: Lint code
        run: yarn admin-web lint

  build:
    runs-on: ubuntu-latest
    needs: [install, build-packages]

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/install-deps
        with:
          hash: ${{ hashFiles('**/yarn.lock') }}

      - uses: actions/cache@v4
        with:
          path: |
            services/**/build
          key: admin-web-build

      - name: Type Check Web
        run: yarn admin-web build

      - name: Build app
        run: yarn admin-web build:app

  docker_build:
    if: ${{ github.head_ref == 'release/alpha' }}
    runs-on: ubuntu-latest
    needs: [install, build-packages, lint, build]

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/install-deps
        with:
          hash: ${{ hashFiles('**/yarn.lock') }}

      - name: Log in to registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build WEB image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./adminWeb.Dockerfile
          push: false
          tags: ${{ env.ADMIN_WEB_IMAGE_NAME }}

