name: Admin Web - Pull Request

on:
  pull_request:
    branches:
      - daily
      - release/alpha
      - master
    paths:
      - ".github/workflows/**"
      - "packages/@liexp/**/src/**"
      - "services/admin-web/**"
env:
  ADMIN_WEB_IMAGE_NAME: liexp-admin-web

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/install-deps
        with:
          hash: ${{ hashFiles('**/yarn.lock') }}

  build-packages:
    runs-on: ubuntu-latest
    needs: [install]
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/install-deps
        with:
          hash: ${{ hashFiles('**/yarn.lock') }}

      - uses: ./.github/actions/build-packages
        with:
          hash: ${{ github.sha }}

  lint:
    runs-on: ubuntu-latest
    needs: [install, build-packages]
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/install-deps
        with:
          hash: ${{ hashFiles('**/yarn.lock') }}

      - uses: ./.github/actions/build-packages
        with:
          hash: ${{ github.sha }}

      - name: Lint code
        run: yarn admin-web lint

  build:
    runs-on: ubuntu-latest
    needs: [install, build-packages]

    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/install-deps
        with:
          hash: ${{ hashFiles('**/yarn.lock') }}

      - uses: actions/cache@v3
        with:
          path: |
            services/**/build
          key: admin-web-build

      - name: Type Check Web
        run: yarn admin-web build

      - name: Build app with Webpack
        run: yarn admin-web build:app

      - name: Log in to registry
        # This is where you will update the personal access token to GITHUB_TOKEN
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

      - name: Build Web image
        run: docker build . --file adminWeb.Dockerfile --tag $ADMIN_WEB_IMAGE_NAME --label "runnumber=${GITHUB_RUN_ID}"
