name: Admin Web - Pull Request

on:
  pull_request:
    branches:
      - daily
      - release/alpha
      - master
    paths:
      - "packages/**"
      - "services/admin-web/**"

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "yarn"
          cache-dependency-path: yarn.lock

      - name: Install modules
        # if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn

  lint:
    runs-on: ubuntu-latest
    needs: [install]
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "yarn"
          cache-dependency-path: yarn.lock

      - name: Lint code
        run: yarn admin-web lint

  build:
    runs-on: ubuntu-latest
    needs: [install]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "yarn"
          cache-dependency-path: yarn.lock

      - name: Build web
        run: yarn admin-web build
        env:
          DISABLE_ESLINT_PLUGIN: true
          SKIP_PREFLIGHT_CHECK: true

  tests-spec:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "yarn"
          cache-dependency-path: yarn.lock

      - name: Download build artifact
        uses: actions/download-artifact@v2
        with:
          name: build

      - name: Run tests SPEC
        run: yarn admin-web test