name: API - Pull Request

on:
  pull_request:
    branches:
      - daily
      - release/alpha
      - master
    paths:
      - ".github/workflows/**"
      - "packages/@liexp/**/src/**"
      - "services/ai-bot/**"

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/install-deps
        with:
          hash: ${{ hashFiles('**/pnpm-lock.yaml') }}

  build-packages:
    runs-on: ubuntu-latest
    needs: [install]
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/install-deps
        with:
          hash: ${{ hashFiles('**/pnpm-lock.yaml') }}

      - uses: ./.github/actions/build-packages
        with:
          hash: ${{ github.sha }}

  lint:
    runs-on: ubuntu-latest
    needs: [install, build-packages]
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/install-deps
        with:
          hash: ${{ hashFiles('**/pnpm-lock.yaml') }}

      - uses: ./.github/actions/build-packages
        with:
          hash: ${{ github.sha }}

      - name: Lint code
        run: pnpm ai-bot lint

  build:
    needs: [install, build-packages]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/install-deps
        with:
          hash: ${{ hashFiles('**/pnpm-lock.yaml') }}

      - uses: ./.github/actions/build-packages
        with:
          hash: ${{ github.sha }}

      - name: Run migrations
        run: pnpm ai-bot build

  # docker_build:
  #   if: ${{ github.head_ref == 'release/alpha' }}
  #   needs: [install, build-packages, lint, build]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4

  #     - uses: ./.github/actions/install-deps
  #       with:
  #         hash: ${{ hashFiles('**/pnpm-lock.yaml') }}

  #     - name: Log in to registry
  #       uses: docker/login-action@v3
  #       with:
  #         registry: ghcr.io
  #         username: ${{ github.actor }}
  #         password: ${{ secrets.GITHUB_TOKEN }}

  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v3

  #     - name: Build API image
  #       uses: docker/build-push-action@v5
  #       with:
  #         context: .
  #         file: ./api.Dockerfile
  #         push: false
  #         tags: ${{ env.API_IMAGE_NAME }}
