name: AI Bot - Pull Request

on:
  pull_request:
    branches:
      - daily
      - release/alpha
      - master
    paths:
      - ".github/workflows/**"
      - "packages/@liexp/**/src/**"
      - "services/ai-bot/**"

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/install-deps
        with:
          hash: ${{ hashFiles('**/pnpm-lock.yaml') }}

  build-packages:
    runs-on: ubuntu-latest
    needs: [install]
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/install-deps
        with:
          hash: ${{ hashFiles('**/pnpm-lock.yaml') }}

      - uses: ./.github/actions/build-packages
        with:
          hash: ${{ github.sha }}

  lint:
    runs-on: ubuntu-latest
    needs: [install, build-packages]
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/install-deps
        with:
          hash: ${{ hashFiles('**/pnpm-lock.yaml') }}

      - uses: ./.github/actions/build-packages
        with:
          hash: ${{ github.sha }}

      - name: Lint code
        run: pnpm ai-bot lint

  build:
    needs: [install, build-packages]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/install-deps
        with:
          hash: ${{ hashFiles('**/pnpm-lock.yaml') }}

      - uses: ./.github/actions/build-packages
        with:
          hash: ${{ github.sha }}

      - name: Build
        run: pnpm ai-bot build