name: Deploy Alpha API

on:
  push:
    branches:
      - release/alpha
    paths:
      - ".github/workflows/**"
      - "packages/@liexp/core/**"
      - "packages/@liexp/shared/**"
      - "packages/@liexp/backend/**"
      - "packages/@liexp/ui/**"

env:
  API_IMAGE_TAG: ghcr.io/lies-exposed/liexp-api:alpha-latest

jobs:
  deploy-api:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4


      - name: Log in to registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_IO_USERNAME }}
          password: ${{ secrets.GHCR_IO_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build API image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./api.Dockerfile
          push: true
          tags: ${{ env.API_IMAGE_TAG }}